# Generated by Django 5.2.6 on 2025-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Размер (байт)"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Тип содержимого"
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Расширение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
