# Generated by Django 5.2.6 on 2025-09-20 10:17

import uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(
                upload_to="uploads/%Y/%m/%d/",
                validators=[uploader.models.validate_file_size_512mb],
                verbose_name="Файл",
            ),
        ),
    ]
